<?php

namespace App\Http\Requests\Admin\Post;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|string',
            'content' => 'required|string',
            'preview_image' => 'required|file',
            'main_image' => 'required|file',
            'category_id' => 'required|integer|exists:categories,id',
            'tag_ids' => 'nullable|array',
            'tag_ids.*' => 'nullable|integer|exists:tags,id',
        ];
    }

    // используем зарезервированный метод для норм обработки ошибок
    public function messages()
    {
        // если не поставить свой массив возврат по умолчанию, что есть в parent::messages()
        //return parent::messages(); // TODO: Change the autogenerated stub

        return [
            'title.required' => 'this field is required to fill in',
            'title.string' => 'the data must be of a lowercase type',
        ];
    }
}
